py27 installed: certifi==2015.9.6.2,coverage==4.0.2,enum34==1.0.4,flake8==2.5.0,funcsigs==0.4,futures==3.0.3,httpretty==0.8.10,isodate==0.5.4,keyring==5.6,mccabe==0.3.1,mock==1.3.0,oauthlib==1.0.3,pbr==1.8.1,pep8==1.5.7,pyflakes==1.0.0,requests==2.7.0,requests-oauthlib==0.5.0,six==1.10.0,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='587'
py27 runtests: commands[0] | coverage run -m unittest discover -s ./AcceptanceTests -p *tests.py -v
acceptance_tests (unittest.loader.ModuleImportFailure) ... ERROR
dictionary_tests (unittest.loader.ModuleImportFailure) ... ERROR
file_tests (unittest.loader.ModuleImportFailure) ... ERROR
required_optional_tests (unittest.loader.ModuleImportFailure) ... ERROR
url_tests (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: acceptance_tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: acceptance_tests
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\AcceptanceTests\acceptance_tests.py", line 17, in <module>
    from msrest.exceptions import DeserializationError
ImportError: No module named msrest.exceptions


======================================================================
ERROR: dictionary_tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: dictionary_tests
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\AcceptanceTests\dictionary_tests.py", line 12, in <module>
    from msrest.exceptions import DeserializationError
ImportError: No module named msrest.exceptions


======================================================================
ERROR: file_tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: file_tests
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\AcceptanceTests\file_tests.py", line 14, in <module>
    from msrest.exceptions import DeserializationError
ImportError: No module named msrest.exceptions


======================================================================
ERROR: required_optional_tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: required_optional_tests
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\AcceptanceTests\required_optional_tests.py", line 12, in <module>
    from msrest.exceptions import DeserializationError
ImportError: No module named msrest.exceptions


======================================================================
ERROR: url_tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: url_tests
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\AcceptanceTests\url_tests.py", line 14, in <module>
    from msrest.exceptions import DeserializationError
ImportError: No module named msrest.exceptions


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
ERROR: InvocationError: 'D:\\Github\\autorest\\AutoRest\\Generators\\Python\\Python.Tests\\.tox\\py27\\Scripts\\coverage.EXE run -m unittest discover -s ./AcceptanceTests -p *tests.py -v'
py35 create: D:\Github\autorest\AutoRest\Generators\Python\Python.Tests\.tox\py35
ERROR: InterpreterNotFound: python3.5
___________________________________ summary ___________________________________
ERROR:   py27: commands failed
ERROR:   py35: InterpreterNotFound: python3.5
